PROCESS BEFORE OUTPUT.
 MODULE set_container_9100.

 CALL SUBSCREEN sub_screen_9200 INCLUDING
 'ZTT0MACENG_M_ORQUESTRADOR_V2' '9200'.

PROCESS AFTER INPUT.

 CALL SUBSCREEN sub_screen_9200.

* MODULE USER_COMMAND_9100.